version: '3.9'

services:
  db:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
    command: ["npm", "start"]

volumes:
  db_data: